# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # builds needed files
      - name: build
        run: |
          chmod +x bootstrap
          ./bootstrap
          ./comp example.py example.v
          pwd
      # runs compiled python
      - name: run
        run: ./example
      - name: upload artifact
        uses: actions/actions/upload-artifact@v2
        with:
          name: test
          path: /home/runner/work/py-compiler/py-compiler/example
          
